### ISSUE TITLE
env: node\r: No such file or directory

### ISSUE THREAD

**Issue by sunshineo** [lydell/hash-filename#1]
When I try to use this I got this error
env: node\r: No such file or directory

I'm on Mac. It seems a \r need to be replaced with proper \n that works in all operating systems. But I was not able to find it.

**Comment by lydell** [comment]
Ouch, that sucks. I'd recommend switching to [keithamus/hashmark](https://github.com/keithamus/hashmark) instead. Hopefully I'll remember to deprecate this module. EDIT: But first the issue referenced by @sunshineo must be resolved.

**Comment by sunshineo** [comment]
@lydell That one does not support blob as it claims. See https://github.com/keithamus/hashmark/issues/1 . Why do you want to deprecate this module? Why can't it be fixed?

**Comment by lydell** [comment]
Sure, it could be fixed, but it does not seem worth it since hashmark looks superior to me.

**Comment by sunshineo** [comment]
@lydell I'm not an expert on JavaScript build tools, but I feel the other project wrapped too much things. I agree this project is more basic. But the output can be then piped to other tasks to rename files or replace the <script> tags in html. Maybe the other project should use this one as the building block.

**Comment by lydell** [comment]
Note that hash-filename only supports globs in terminals that support globs, so you will not get Windows support.

**Comment by lydell** [comment]
I’ve published 1.0.4 now, and it works for me at least.
